# Generated by Django 5.2.1 on 2025-06-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('level_of_study', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=10)),
                ('year_of_course', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseTotalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_teaching_sessions', models.IntegerField(blank=True, null=True)),
                ('total_attended', models.IntegerField(blank=True, null=True)),
                ('total_non_attended', models.IntegerField(blank=True, null=True)),
                ('total_attendance_percent', models.FloatField(blank=True, null=True)),
                ('total_assessments', models.IntegerField(blank=True, null=True)),
                ('total_submitted', models.IntegerField(blank=True, null=True)),
                ('total_non_submission', models.IntegerField(blank=True, null=True)),
                ('total_submitted_percent', models.FloatField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_sessions', models.IntegerField(blank=True, null=True)),
                ('total_attended', models.IntegerField(blank=True, null=True)),
                ('non_attendance', models.IntegerField(blank=True, null=True)),
                ('attendance_percent', models.FloatField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assessments', models.IntegerField(blank=True, null=True)),
                ('submitted', models.IntegerField(blank=True, null=True)),
                ('non_submission', models.IntegerField(blank=True, null=True)),
                ('submitted_percent', models.FloatField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.enrollment')),
            ],
        ),
    ]
