# Generated by Django 5.2.1 on 2025-07-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='coursetotalstats',
            name='course',
        ),
    ]
