# Generated by Django 5.2.1 on 2025-07-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_assessment_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetotalstats',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.course'),
        ),
    ]
