# Generated by Django 5.2.1 on 2025-07-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_coursetotalstats_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='total_assessments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_attendance_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_attended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_non_attended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_non_submission',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_submitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_submitted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_teaching_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
