# Generated by Django 5.2.1 on 2025-07-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_enrollment_total_assessments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('teaching_sessions', models.IntegerField(blank=True, null=True)),
                ('attended', models.IntegerField(blank=True, null=True)),
                ('non_attended', models.IntegerField(blank=True, null=True)),
                ('attendance_percent', models.FloatField(blank=True, null=True)),
                ('assessments_total', models.IntegerField(blank=True, null=True)),
                ('assessments_submitted', models.IntegerField(blank=True, null=True)),
                ('assessments_non_submitted', models.IntegerField(blank=True, null=True)),
                ('assessment_submitted_percent', models.FloatField(blank=True, null=True)),
                ('last_attendance_datetime', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.enrollment')),
            ],
        ),
    ]
