# Generated by Django 5.2.1 on 2025-07-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_attendancesnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='CourseTotalStats',
        ),
    ]
